### ISSUE TITLE
Doesn't support traditional Chinese workspace (watson conversation)

### ISSUE THREAD

**Issue by ibmhkdemo01** [watson-developer-cloud/conversation-connector#25]
Hi, 
This app does not work work Watson Conversation service with Traditional Chinese workspace.
Can you please fix ?

**Comment by nyoscar** [comment]
https://github.com/watson-developer-cloud/conversation-connector/issues/29#issuecomment-364994541

**Comment by dgterry** [comment]
If this is for Facebook I believe things should now work due to the current commits. Please let us know if that isn't the case.
