### ISSUE TITLE
connected the slack app to the wcs workspace but didn't get the answer from the bot

### ISSUE THREAD

**Issue by entheos37** [watson-developer-cloud/conversation-connector#27]
Hi

I connected the slack app to the wcs workspace but didn't get the answer from the bot.

I was able to communicate with the @ibmwatson_bot but not my personal slack app @onboarding.

![2018-01-22 2 59 07](https://user-images.githubusercontent.com/16621093/35207293-7f552b64-ff85-11e7-9165-8163245e507e.png)

Also, the cloud functions editor link does not have the url 404 error

[https://console.bluemix.net/openwhisk/editor?env_id=ibm%3Ayp%3Aus-south](url)

How can I communicate with the slack bot app linked to my wcs workspace?

Also how can I modify the cloud function linked to my wcs worksace? I am trying to connect the cloudant db or dash db and update the message method there to enable the <br> code in the wcs output.text.

Thank you!

**Comment by entheos37** [comment]
Hi, https://github.com/watson-developer-cloud/conversation-connector/blob/master/channels/slack/README.md#manual-deployment

By following the manual deployment it is working but just following the process described in the workspace deploy part it is not working. 

I found that this url [https://console.bluemix.net/openwhisk/actions](url) is working for the openwhisk function.

**Comment by aarora91** [comment]
@entheos37 
The first step is for us to make sure you were able to do the manual deploy correctly.

You can access your Cloud Functions actions here: https://console.bluemix.net/openwhisk/actions

You should see a bunch of actions inside the packages-`slack`, `conversation`,`context` and `starter-code`.

Please make sure you added the relevant credentials for your Slack app and Conversation instance in the `providers.json` before you ran `setup.sh`.

Let me know if you see these Cloud Functions.

**Comment by dgterry** [comment]
I'm going to close this as I think the issues reported have been identified and corrected. 

Thank you for pointing out the 404 with the URL. I believe you have found the best replacement, https://console.bluemix.net/openwhisk/actions . We will be updating the Conversation UI to use this in the near future. 

There also was a bug in the UI deploy for Slack that deployed an older version of the call-conversation Cloud Function.  This too has been fixed so the UI deploy should work again. Thank you for reporting these issues. Let us know if you have further questions.
