### ISSUE TITLE
Germany supported?

### ISSUE THREAD

**Issue by data-henrik** [watson-developer-cloud/conversation-connector#29]
Frankfurt (DE) seems to have support for IBM Cloud Functions and Watson Conversation. Is the Conversation Connector supported, too?

**Comment by nyoscar** [comment]
@data-henrik we are evaluating how we can remove the language dependency so that the Conversation Connector would work regardless of language.

**Comment by data-henrik** [comment]
I mean support for the eu-de data center (Frankfurt, Germany), not any spoken language.

**Comment by data-henrik** [comment]
@nyoscar Asking again regarding support for eu-de data center.
