### ISSUE TITLE
Instructions or support for cleanup?

### ISSUE THREAD

**Issue by data-henrik** [watson-developer-cloud/conversation-connector#33]
How can I remove all the objects created by conversation connector? Are there any instructions or even tooling support?

**Comment by dgterry** [comment]
Hello,

The easiest way right now is probably to use the Cloud Functions UI.  If you go here: https://console.bluemix.net/openwhisk/actions you will see a variety of actions, organized by packages, that the Conversation Connector deployed. They follow the naming convention of whatever you named your deploy + _ + package name. So if you called your deploy mydeploy you would see packages like mydeploy_starter-code.  You can delete the package and everything in it via the dotted menu on the right of the action name. 

Alternatively  CLI tooks like wsk have the ability to remove individual assets via comments like ```wsk action delete``` and you could in theory script these commands to delete everything but that might be a bit tedious. 

Hope this helps.

**Comment by data-henrik** [comment]
That does not clear the Cloudant resources

**Comment by dgterry** [comment]
Yes, that's correct, you could goto https://console.bluemix.net/dashboard/apps/ and delete the conversation-connector Cloudant instance using the dotted menu on the right. It will have been deployed to the same org and space as your conversation service if you used the tooling slack deploy. Unfortunately the cleanup is a bit manual at this point but this combined with the Cloud function steps I mentioned earlier should get everything.

**Comment by data-henrik** [comment]
That only works if you have exactly one connector deployed. All connectors store their credentials in the same space. (Ok, search within the database for the correct doc, then delete). You get my point...
