### ISSUE TITLE
Problem with Callback URL for Facebook

### ISSUE THREAD

**Issue by florandres** [watson-developer-cloud/conversation-connector#67]
I have a problem here, with the Webhook setup. It throws me an error message in the Callback URL field. It says "URL cannot be validated" My URL is https://openwhisk.ng.bluemix.net/api/v1/web/Arg-TechSales_Growth-Argentina/facebookrpa_slack/receive.text (I've changed the .json)
<img width="302" alt="image" src="https://user-images.githubusercontent.com/23477761/45109535-3f0ccb00-b116-11e8-8f41-7a404f73667b.png">

Thank you!!

**Comment by MalekBakri** [comment]
hello, did you fix it and how ? thank you
