### ISSUE TITLE
Options / Quick Replies not working

### ISSUE THREAD

**Issue by cl877441** [watson-developer-cloud/conversation-connector#69]
Should the new commits for different response types mean that Options, Pause, Image etc works with Facebook without any need for changes to JSON in Watson dialog?

I have pushed the new commits to my Toolchain but still get a 400 error response whenever triggering dialog that contains Options 

I have been able to 'force' QuickReplies by changing JSON to the following but my understanding of the latest commits is this should no longer be necessary?

{
  "output": {
    "text": {
      "values": [],
      "selection_policy": "sequential"
    },
    "facebook": {
      "message": {
        "text": "Did you have a good experience?",
        "quick_replies": [
          {
            "title": "Yes",
            "payload": "Giving",
            "image_url": "http://example.com/img/red.png",
            "content_type": "text"
          },
          {
            "title": "No",
            "payload": "Receiving",
            "image_url": "http://example.com/img/green.png",
            "content_type": "text"
          }
        ]
      }
    }
  }
}

**Comment by dgterry** [comment]
Yes, the project should now support option, pause, image, and text response types as authored in the tooling UI.  You can certainly still write output.facebook but you shouldn't have to if you want the default processing. Would you mind going into your conversation workspace and sharing the JSON from the advanced JSON editor on the dialog node that you are hitting that gives you the 400? Feel free to mask anything sensitive I'm mostly interested in the structure and if you were able to author something we weren't expecting.
