### ISSUE TITLE
status: 400,           text: 'Neither a page type request nor a verfication type request detected'

### ISSUE THREAD

**Issue by MhmodTayel** [watson-developer-cloud/conversation-connector#71]
status: 400,
          text: 'Neither a page type request nor a verfication type request detected'

what should i do please.

**Comment by dgterry** [comment]
Could you please let me know if you have your bot subscribed to a given page? The code expects that to be the case.  Also, could you please let me know what you are saying to the bot when you experience this problem? No need to share any sensitive text strings...just mostly looking for if you are sending non-text data which isn't really supported. The project should work with text, including text with accents, and some basic emojis.
