### ISSUE TITLE
Problem with portuguese accented words.

### ISSUE THREAD

**Issue by dlimabr** [watson-developer-cloud/conversation-connector#9]
When I write portuguese accented words using the FB messenger it seems the Messenger is losting communication with watson.

Ex: Quem é você? (but if I write "quem e voce" it works fine).

Is There someone facing the same problem?

**Comment by data-henrik** [comment]
FYI: I am currently testing the connector with Slack. I tried German Umlauts, Spanish accents and your sample phrase and they reach WCS and are shown in the log. So it seems an issue with FB Messenger.

**Comment by vitormixd** [comment]
Hi @dlimabr, did you figured it out? I'm facing the same issue =/

**Comment by ljoseppi** [comment]
Hi @dlimabr and @vitormixd, I am also facing this issue. Any Ideas?

**Comment by vitormixd** [comment]
Hi @ljoseppi! I ended using my own implementation of the connections with the watson conversation api.

**Comment by vinistig** [comment]
Hi @dlimabr and @vitormixd, I am also facing this issue. Any Ideas?

**Comment by dgterry** [comment]
Going to close this as I believe the work based on @ljoseppi 's fix should handle this.
